name: Validate Renovate preset

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Validate repository-level Renovate presets
        uses: docker://renovate/renovate:44.121.3@sha256:e0583d0cdba97b1db9e281cd12e07af45f52f3d276f46cca6cc1efba26b635bd
        with:
          entrypoint: /usr/local/sbin/renovate-config-validator
          args: --strict --no-global default.json
