name: Validate Renovate preset

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Validate repository-level Renovate presets
        uses: docker://renovate/renovate:44.61.5@sha256:8f66b39236d349af13b3794138f085bc2f0915597fe026a6387667db5dcc41fb
        with:
          entrypoint: /usr/local/sbin/renovate-config-validator
          args: --strict --no-global default.json
