name: Validate Renovate preset

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Validate repository-level Renovate presets
        uses: docker://renovate/renovate:44.83.2@sha256:c1cb952b2e14a112d0d0c61987a10f60a2626fe9b9c1504436be46a17bd123bc
        with:
          entrypoint: /usr/local/sbin/renovate-config-validator
          args: --strict --no-global default.json
